# Use postgres/example user/password credentials
version: '1.0'

services:

  db:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: 1Qwerty
    ports:
      - 5432:5432
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
