INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Ultimate', 'A high-performance mobile phone.', 659.53, 13, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Ultimate', 'A powerful laptop for professionals.', 788.94, 30, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Pro', 'A stunning 4K TV.', 475.18, 60, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Ultimate', 'A compact and lightweight tablet.', 687.51, 44, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Ultimate', 'Next-gen gaming console.', 590.89, 51, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Pro', 'Precision gaming mouse.', 289.31, 5, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Pro', 'Durable and responsive keys.', 393.75, 34, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Hyper', 'Immersive curved display.', 854.99, 41, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Elite', 'Popular gaming console.', 850.25, 91, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Premium', 'Ergonomic design for office work.', 576.65, 84, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Standard', 'A sleek and modern smartphone.', 880.12, 52, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Hyper', 'Lightweight laptop for daily use.', 607.5, 22, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Elite', 'A large 4K UHD smart TV.', 341.23, 25, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Deluxe', 'A tablet designed for gaming.', 841.69, 83, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Exclusive', 'High-end gaming console.', 363.58, 79, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Standard', 'Ergonomic wireless gaming mouse.', 500.9, 88, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Ultimate', 'RGB lighting for gaming.', 365.22, 61, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Hyper', 'A large ultra-wide monitor.', 537.13, 4, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Smart', 'Enhanced performance gaming console.', 213.44, 19, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Pro', 'Lightweight wireless mouse.', 403.51, 52, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Smart', 'A high-performance mobile phone.', 89.83, 38, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Elite', 'A powerful laptop for professionals.', 507.21, 27, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Ultimate', 'A stunning 4K TV.', 173.21, 99, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Pro', 'A compact and lightweight tablet.', 250.24, 32, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Elite', 'Next-gen gaming console.', 884.64, 48, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Royal', 'Precision gaming mouse.', 290.29, 50, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Advanced', 'Durable and responsive keys.', 481.68, 50, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Ultimate', 'Immersive curved display.', 631.23, 47, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Hyper', 'Popular gaming console.', 351.42, 31, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Standard', 'Ergonomic design for office work.', 224.9, 1, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Advanced', 'A sleek and modern smartphone.', 913.09, 70, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Standard', 'Lightweight laptop for daily use.', 672.33, 31, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Premium', 'A large 4K UHD smart TV.', 284.28, 39, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Pro', 'A tablet designed for gaming.', 700.85, 16, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Elite', 'High-end gaming console.', 509.81, 11, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Pro', 'Ergonomic wireless gaming mouse.', 553.69, 16, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Smart', 'RGB lighting for gaming.', 792.43, 8, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Smart', 'A large ultra-wide monitor.', 903.04, 39, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Royal', 'Enhanced performance gaming console.', 964.65, 79, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Elite', 'Lightweight wireless mouse.', 359.75, 33, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Standard', 'A high-performance mobile phone.', 201.48, 89, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Pro', 'A powerful laptop for professionals.', 348.87, 44, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Standard', 'A stunning 4K TV.', 626.64, 54, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Royal', 'A compact and lightweight tablet.', 613.84, 51, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Exclusive', 'Next-gen gaming console.', 43.04, 76, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Premium', 'Precision gaming mouse.', 88.6, 36, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Deluxe', 'Durable and responsive keys.', 636.8, 28, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Deluxe', 'Immersive curved display.', 782.6, 3, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Premium', 'Popular gaming console.', 237.32, 28, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Deluxe', 'Ergonomic design for office work.', 734.39, 9, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Ultimate', 'A sleek and modern smartphone.', 151.59, 53, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Elite', 'Lightweight laptop for daily use.', 76.02, 39, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Ultimate', 'A large 4K UHD smart TV.', 171.21, 58, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Standard', 'A tablet designed for gaming.', 422.57, 93, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Pro', 'High-end gaming console.', 733.31, 86, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Ultimate', 'Ergonomic wireless gaming mouse.', 54.92, 89, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Pro', 'RGB lighting for gaming.', 66.03, 63, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Premium', 'A large ultra-wide monitor.', 850.9, 93, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Deluxe', 'Enhanced performance gaming console.', 125.68, 78, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Hyper', 'Lightweight wireless mouse.', 630.55, 7, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Advanced', 'A high-performance mobile phone.', 866.91, 25, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Standard', 'A powerful laptop for professionals.', 378.77, 79, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Hyper', 'A stunning 4K TV.', 589.18, 60, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Standard', 'A compact and lightweight tablet.', 805.41, 53, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Premium', 'Next-gen gaming console.', 327.72, 92, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Exclusive', 'Precision gaming mouse.', 43.46, 73, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Premium', 'Durable and responsive keys.', 602.1, 27, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Premium', 'Immersive curved display.', 996.73, 100, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Advanced', 'Popular gaming console.', 772.08, 83, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Hyper', 'Ergonomic design for office work.', 237.27, 2, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Hyper', 'A sleek and modern smartphone.', 134.85, 65, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Premium', 'Lightweight laptop for daily use.', 139.88, 13, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Deluxe', 'A large 4K UHD smart TV.', 307.3, 38, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Advanced', 'A tablet designed for gaming.', 697.35, 84, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Premium', 'High-end gaming console.', 680.78, 25, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Advanced', 'Ergonomic wireless gaming mouse.', 105.48, 15, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Elite', 'RGB lighting for gaming.', 37.59, 70, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Deluxe', 'A large ultra-wide monitor.', 966.6, 74, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Exclusive', 'Enhanced performance gaming console.', 851.87, 92, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Deluxe', 'Lightweight wireless mouse.', 784.65, 89, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Elite', 'A high-performance mobile phone.', 627.88, 29, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Exclusive', 'A powerful laptop for professionals.', 42.28, 55, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Advanced', 'A stunning 4K TV.', 721.01, 56, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Advanced', 'A compact and lightweight tablet.', 222.73, 10, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Standard', 'Next-gen gaming console.', 594.88, 54, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Standard', 'Precision gaming mouse.', 578.46, 49, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Ultimate', 'Durable and responsive keys.', 168.55, 51, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Elite', 'Immersive curved display.', 44.56, 21, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Exclusive', 'Popular gaming console.', 781.36, 51, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Royal', 'Ergonomic design for office work.', 189.75, 26, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Premium', 'A sleek and modern smartphone.', 46.32, 99, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Royal', 'Lightweight laptop for daily use.', 515.41, 14, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Hyper', 'A large 4K UHD smart TV.', 397.14, 54, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Elite', 'A tablet designed for gaming.', 820.52, 38, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Ultimate', 'High-end gaming console.', 858.4, 14, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Hyper', 'Ergonomic wireless gaming mouse.', 652.72, 23, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Hyper', 'RGB lighting for gaming.', 67.53, 38, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Ultimate', 'A large ultra-wide monitor.', 521.03, 98, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Standard', 'Enhanced performance gaming console.', 955.99, 54, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Exclusive', 'Lightweight wireless mouse.', 40.66, 20, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Royal', 'A high-performance mobile phone.', 350.53, 85, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Royal', 'A powerful laptop for professionals.', 876.23, 29, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Premium', 'A stunning 4K TV.', 45.48, 40, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Hyper', 'A compact and lightweight tablet.', 490.19, 93, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Deluxe', 'Next-gen gaming console.', 691.5, 95, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Deluxe', 'Precision gaming mouse.', 228.47, 19, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Royal', 'Durable and responsive keys.', 36.65, 92, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Royal', 'Immersive curved display.', 668.74, 81, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Standard', 'Popular gaming console.', 326.95, 4, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Advanced', 'Ergonomic design for office work.', 559.45, 1, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Royal', 'A sleek and modern smartphone.', 955.02, 90, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Smart', 'Lightweight laptop for daily use.', 567.1, 28, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Pro', 'A large 4K UHD smart TV.', 424.23, 48, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Premium', 'A tablet designed for gaming.', 812.48, 56, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Deluxe', 'High-end gaming console.', 805.14, 13, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Premium', 'Ergonomic wireless gaming mouse.', 804.01, 99, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Standard', 'RGB lighting for gaming.', 460.15, 70, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Royal', 'A large ultra-wide monitor.', 875.27, 5, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Elite', 'Enhanced performance gaming console.', 382.72, 69, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Ultimate', 'Lightweight wireless mouse.', 149.95, 17, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Hyper', 'A high-performance mobile phone.', 85.78, 86, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Premium', 'A powerful laptop for professionals.', 740.53, 76, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Royal', 'A stunning 4K TV.', 591.31, 37, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Premium', 'A compact and lightweight tablet.', 932.76, 48, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Advanced', 'Next-gen gaming console.', 263.46, 15, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Hyper', 'Precision gaming mouse.', 727.72, 89, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Exclusive', 'Durable and responsive keys.', 200.21, 85, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Smart', 'Immersive curved display.', 460.7, 91, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Smart', 'Popular gaming console.', 372.45, 93, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Smart', 'Ergonomic design for office work.', 96.37, 60, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Pro', 'A sleek and modern smartphone.', 684.86, 92, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Ultimate', 'Lightweight laptop for daily use.', 514.43, 66, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Advanced', 'A large 4K UHD smart TV.', 315.84, 63, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Exclusive', 'A tablet designed for gaming.', 739.37, 58, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Hyper', 'High-end gaming console.', 424.58, 50, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Royal', 'Ergonomic wireless gaming mouse.', 966.38, 76, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Royal', 'RGB lighting for gaming.', 888.67, 3, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Advanced', 'A large ultra-wide monitor.', 749.62, 4, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Premium', 'Enhanced performance gaming console.', 888.55, 76, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Standard', 'Lightweight wireless mouse.', 779.37, 27, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Deluxe', 'A high-performance mobile phone.', 687.65, 84, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Smart', 'A powerful laptop for professionals.', 707.16, 70, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Deluxe', 'A stunning 4K TV.', 590.21, 16, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Special 143', 'A compact and lightweight tablet.', 311.56, 25, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Hyper', 'Next-gen gaming console.', 771.39, 3, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Elite', 'Precision gaming mouse.', 306.14, 34, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Hyper', 'Durable and responsive keys.', 799.64, 77, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Advanced', 'Immersive curved display.', 485.89, 9, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Deluxe', 'Popular gaming console.', 925.04, 97, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Ultimate', 'Ergonomic design for office work.', 268.91, 0, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Elite', 'A sleek and modern smartphone.', 757.02, 24, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Advanced', 'Lightweight laptop for daily use.', 70.12, 6, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Smart', 'A large 4K UHD smart TV.', 790.02, 35, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Smart', 'A tablet designed for gaming.', 527.41, 94, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Advanced', 'High-end gaming console.', 756.31, 55, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Elite', 'Ergonomic wireless gaming mouse.', 106.24, 77, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Advanced', 'RGB lighting for gaming.', 443.68, 92, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Elite', 'A large ultra-wide monitor.', 302.93, 67, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Ultimate', 'Enhanced performance gaming console.', 460.27, 55, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Premium', 'Lightweight wireless mouse.', 725.14, 27, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Premium', 'A high-performance mobile phone.', 839.6, 84, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Advanced', 'A powerful laptop for professionals.', 71.03, 20, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Exclusive', 'A stunning 4K TV.', 189.18, 53, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Exclusive', 'A compact and lightweight tablet.', 729.42, 96, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Royal', 'Next-gen gaming console.', 626.09, 79, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Advanced', 'Precision gaming mouse.', 901.09, 27, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Special 166', 'Durable and responsive keys.', 899.65, 14, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Standard', 'Immersive curved display.', 575.73, 82, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Royal', 'Popular gaming console.', 484.05, 43, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Elite', 'Ergonomic design for office work.', 733.34, 20, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Exclusive', 'A sleek and modern smartphone.', 158.92, 25, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Exclusive', 'Lightweight laptop for daily use.', 823.57, 59, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Royal', 'A large 4K UHD smart TV.', 305.32, 18, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Ultimate', 'A tablet designed for gaming.', 814.22, 20, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Standard', 'High-end gaming console.', 120.91, 57, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Exclusive', 'Ergonomic wireless gaming mouse.', 638.57, 53, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Deluxe', 'RGB lighting for gaming.', 180.67, 15, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Exclusive', 'A large ultra-wide monitor.', 154.41, 20, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Advanced', 'Enhanced performance gaming console.', 29.6, 2, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Advanced', 'Lightweight wireless mouse.', 402.01, 46, 'mouse', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mobile X1 Exclusive', 'A high-performance mobile phone.', 978.45, 83, 'mobile', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Pro 15 Deluxe', 'A powerful laptop for professionals.', 791.14, 80, 'laptops', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra HD TV Elite', 'A stunning 4K TV.', 328.16, 82, 'TV', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Tablet Mini Smart', 'A compact and lightweight tablet.', 544.42, 68, 'tablets', 'White', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Series X Special 184', 'Next-gen gaming console.', 571.69, 52, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Mouse X Smart', 'Precision gaming mouse.', 425.14, 19, 'mouse', 'Red', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Mechanical Keyboard Standard', 'Durable and responsive keys.', 724.59, 18, 'keyboard', 'Blue', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Curved Monitor Exclusive', 'Immersive curved display.', 778.32, 5, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Ultimate', 'Popular gaming console.', 452.28, 57, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Office Mouse Pro', 'Ergonomic design for office work.', 690.3, 56, 'mouse', 'Gray', 3);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Smartphone Y Smart', 'A sleek and modern smartphone.', 307.92, 99, 'mobile', 'Silver', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Laptop Air 13 Deluxe', 'Lightweight laptop for daily use.', 237.0, 100, 'laptops', 'Gray', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('4K Smart TV Standard', 'A large 4K UHD smart TV.', 350.36, 20, 'TV', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Gaming Tablet 10 Royal', 'A tablet designed for gaming.', 703.44, 47, 'tablets', 'Red', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Xbox Elite Royal', 'High-end gaming console.', 859.94, 26, 'xbox', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Wireless Gaming Mouse Smart', 'Ergonomic wireless gaming mouse.', 910.79, 69, 'mouse', 'Blue', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('RGB Mechanical Keyboard Special 196', 'RGB lighting for gaming.', 270.34, 66, 'keyboard', 'Black', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Ultra Wide Monitor Special 197', 'A large ultra-wide monitor.', 483.35, 73, 'monitor', 'Black', 4);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Playstation 5 Pro Pro', 'Enhanced performance gaming console.', 563.56, 43, 'playstation', 'White', 5);
INSERT INTO items (product_name, description, price, quantity, category, item_color, rating) VALUES ('Compact Wireless Mouse Royal', 'Lightweight wireless mouse.', 310.98, 30, 'mouse', 'White', 3);
